language: node_js
node_js: lts/*
cache:
  npm: false
before_script:
script:
- yarn install
- yarn build
deploy:
  local_dir: .vuepress/dist/
  provider: pages
  skip_cleanup: true
  name: Travis Build Bot
  keep_history: true
  on:
    branch: master
  target_branch: gh-pages
  # committer_from_gh: true
  # allow_empty_commit: true
  github_token:
    secure: i5rv28q5Y9MxOY9dBW2OQLac+nRB8ZENLPNP/qWsDsocbR4ACusE/843pyzRxaPaNgbxBwvEDcZQncWEK+OWDuvw7BIifqx4iopGOuvhy9QDgtzOsWUg1yCOWWxQzksne4YtYYqESKvn2E9zKOaFNRitPsSeMRtc6a/0I2kynWxm4YdLwutdGb8tZ1k1+Y0OpV2Ybv3qxCGRa6Tp0XDulGQczWbzVN3g2CMgust7UlmcfHoqW5kZbyBpCL4Q/DxC9YGWtMIsAVQ5S7yPcM6jxrJ4Ehj9B6LJzaoCwMEAfnhuc4O2PsrnSDIkWXRCbxhrOQD1u+VPuwnmWv0twBxEXG/nYgh/bVc5tFJlGSNqAfFcqgQIkMb1o8I+WVYZHVIXJxYdcHRNAPOw4bHLmZ3UCZHNPlPPH0pnTCzYSlyEGbKuq3DVC893jPqzRbaozOYjmb3+aC3/jpktc2SEasnkubAuBIxu6ugYAcy8L1nYtCxF8EBmLTTfg5AHVZ2CaKzylmcJit8N7ZykCk/y2JGfpSoc3xflMAO12Au4FIqEZOpv+jks3/r2ttzjohleMEYbLpIKTZZH3avec9fc6WGBlcK9/YqiorIHfCBu3nFWIrMfyr4virSbaYrWEaxjYWvvu/4nP+DKqPeIpIUkbNH9AUDUMS3Qi+fIHT3TqUyvT4E=
